//! KiCad `.kicad_sch` schematic export from layout data.
//!
//! Generates a KiCad 7+ schematic file with components placed at the layout
//! positions and wires routed along the layout paths. This gives users a
//! readable schematic — not the tangled mess that KiCad's default import
//! produces.

use crate::types::*;
use pedalkernel::dsl::{ComponentKind, PedalDef};
use std::fmt::Write;

/// Scale factor from layout units to KiCad mils (1 layout unit ≈ 5 mils).
const SCALE: f32 = 5.0;

/// Export a layout + pedal definition to KiCad `.kicad_sch` format.
pub fn export_kicad_schematic(layout: &Layout, pedal: &PedalDef) -> String {
    let mut out = String::with_capacity(8192);

    write_header(&mut out, layout);
    write_components(&mut out, layout, pedal);
    write_wires(&mut out, layout);
    write_power_symbols(&mut out, layout);
    write_footer(&mut out);

    out
}

fn write_header(out: &mut String, layout: &Layout) {
    let w = layout.bounds.width * SCALE;
    let h = layout.bounds.height * SCALE;

    writeln!(out, "(kicad_sch (version 20230121) (generator pedalkernel-layout)").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "  (uuid \"00000000-0000-0000-0000-000000000001\")").unwrap();
    writeln!(out, "  (paper \"A3\")").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "  (title_block\n    (title \"{name}\")\n    (comment 1 \"Generated by PedalKernel Layout Engine\")\n    (comment 2 \"Canvas: {w:.0} x {h:.0} mils\")\n  )",
        name = "PedalKernel Circuit",
    )
    .unwrap();
    writeln!(out).unwrap();
}

fn write_components(out: &mut String, layout: &Layout, pedal: &PedalDef) {
    // Build a lookup from component name to ComponentDef
    let comp_map: std::collections::HashMap<&str, &pedalkernel::dsl::ComponentDef> = pedal
        .components
        .iter()
        .map(|c| (c.id.as_str(), c))
        .collect();

    for (idx, placed) in layout.components.iter().enumerate() {
        let comp_def = comp_map.get(placed.name.as_str());
        let (lib_symbol, ref_prefix) = comp_def
            .map(|c| kicad_symbol_ref(&c.kind))
            .unwrap_or(("Device:R", "X"));

        let x = placed.x * SCALE;
        let y = placed.y * SCALE;
        let angle = placed.orientation as f32;

        writeln!(out, "  (symbol (lib_id \"{lib_symbol}\") (at {x:.1} {y:.1} {angle:.0})").unwrap();
        writeln!(out, "    (uuid \"{:08x}-0000-0000-0000-{:012x}\")", idx + 1, idx + 1).unwrap();
        writeln!(
            out,
            "    (property \"Reference\" \"{ref_prefix}{name}\" (at {x:.1} {y_ref:.1} 0)",
            name = placed.name,
            y_ref = y - 15.0
        )
        .unwrap();
        writeln!(out, "      (effects (font (size 1.27 1.27)))").unwrap();
        writeln!(out, "    )").unwrap();

        if let Some(label) = &placed.label {
            writeln!(
                out,
                "    (property \"Value\" \"{label}\" (at {x:.1} {y_val:.1} 0)",
                y_val = y + 15.0
            )
            .unwrap();
            writeln!(out, "      (effects (font (size 1.27 1.27)))").unwrap();
            writeln!(out, "    )").unwrap();
        }

        writeln!(out, "  )").unwrap();
        writeln!(out).unwrap();
    }
}

fn write_wires(out: &mut String, layout: &Layout) {
    for wire in &layout.wires {
        for seg in wire.points.windows(2) {
            let x1 = seg[0][0] * SCALE;
            let y1 = seg[0][1] * SCALE;
            let x2 = seg[1][0] * SCALE;
            let y2 = seg[1][1] * SCALE;

            writeln!(out, "  (wire (pts (xy {x1:.1} {y1:.1}) (xy {x2:.1} {y2:.1})))").unwrap();
        }
    }
    writeln!(out).unwrap();
}

fn write_power_symbols(out: &mut String, layout: &Layout) {
    for rail in &layout.supply_rails {
        let y = rail.y * SCALE;
        let symbol = if rail.name == "vcc" { "power:VCC" } else { "power:GND" };
        let label = rail.name.to_uppercase();

        writeln!(out, "  (symbol (lib_id \"{symbol}\") (at 50.0 {y:.1} 0)").unwrap();
        writeln!(out, "    (uuid \"rail-{name}\")", name = rail.name).unwrap();
        writeln!(
            out,
            "    (property \"Reference\" \"#{label}\" (at 50.0 {y_ref:.1} 0)",
            y_ref = y - 10.0
        )
        .unwrap();
        writeln!(out, "      (effects (font (size 1.27 1.27)) hide)").unwrap();
        writeln!(out, "    )").unwrap();
        writeln!(out, "  )").unwrap();
        writeln!(out).unwrap();
    }
}

fn write_footer(out: &mut String) {
    writeln!(out, ")").unwrap();
}

/// Map a ComponentKind to a KiCad library symbol reference and reference prefix.
fn kicad_symbol_ref(kind: &ComponentKind) -> (&'static str, &'static str) {
    match kind {
        ComponentKind::Resistor(_) => ("Device:R", "R"),
        ComponentKind::Capacitor(_) => ("Device:C", "C"),
        ComponentKind::Inductor(_) => ("Device:L", "L"),
        ComponentKind::DiodePair(_) | ComponentKind::Diode(_) => ("Device:D", "D"),
        ComponentKind::Zener(_) => ("Device:D_Zener", "D"),
        ComponentKind::Potentiometer(..) => ("Device:R_Potentiometer", "RV"),
        ComponentKind::Npn(_) => ("Device:Q_NPN_BCE", "Q"),
        ComponentKind::Pnp(_) => ("Device:Q_PNP_BCE", "Q"),
        ComponentKind::OpAmp(_) => ("Amplifier_Operational:TL072", "U"),
        ComponentKind::NJfet(_) => ("Device:Q_NJFET_DGS", "J"),
        ComponentKind::PJfet(_) => ("Device:Q_PJFET_DGS", "J"),
        ComponentKind::Triode(_) => ("Valve:ECC83", "V"),
        ComponentKind::Pentode(_) => ("Valve:EL84", "V"),
        ComponentKind::Nmos(_) => ("Device:Q_NMOS_DGS", "Q"),
        ComponentKind::Pmos(_) => ("Device:Q_PMOS_DGS", "Q"),
        ComponentKind::Transformer(_) => ("Transformer:Transformer_1P_1S", "T"),
        ComponentKind::Photocoupler(_) => ("Isolator:PC817", "OC"),
        ComponentKind::Bbd(_) => ("Analog_Delay:MN3207", "IC"),
        ComponentKind::Neon(_) => ("Device:Lamp_Neon", "NE"),
        ComponentKind::Vco(_) => ("Oscillator:CEM3340", "U"),
        ComponentKind::Vcf(_) => ("Analog:CEM3320", "U"),
        ComponentKind::Vca(_) => ("Analog:SSM2164", "U"),
        ComponentKind::Comparator(_) => ("Comparator:LM311", "U"),
        ComponentKind::AnalogSwitch(_) => ("Analog_Switch:CD4066", "U"),
        ComponentKind::MatchedNpn(_) | ComponentKind::MatchedPnp(_) => {
            ("Transistor_BJT:SSM2210", "Q")
        }
        ComponentKind::Tempco(..) => ("Device:R", "RT"),
        ComponentKind::CapSwitched(_) => ("Device:C", "C"),
        ComponentKind::InductorSwitched(_) => ("Device:L", "L"),
        ComponentKind::ResistorSwitched(_) => ("Device:R", "R"),
        ComponentKind::RotarySwitch(_) => ("Switch:SW_Rotary4", "SW"),
        ComponentKind::Switch(_) => ("Switch:SW_SPDT", "SW"),
        _ => ("Device:R", "X"),
    }
}
